apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
spec:
  clusterIP: None
  selector:
    env: dev
    app: frontend
  ports:
    - port: 80
      protocol: TCP
      name: port-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-set
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: container01
          image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
spec:
  clusterIP: None
  selector:
    env: dev
    app: backend
  ports:
    - port: 80
      protocol: TCP
      name: port-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-set-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: backend
  template:
    metadata:
      labels:
        env: dev
        app: backend
    spec:
      containers:
        - name: container01
          image: nginx:alpine
