apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
---
apiVersion: v1
kind: Secret
metadata:
  namespace: ns-dev
  name: sc-parameters
type: Opaque
data:
  db_host: bG9jYWxob3N0
  db_port: MzMwNg==
  db_user: dXNlcjEyMw==
  db_pass: MTIzNDU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
  namespace: ns-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      namespace: ns-dev
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: container01
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: db_user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: sc-parameters
                  key: db_pass
