services:
  server-web:
    container_name: server-web
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/app:ro
    cpus: 0.5
    mem_limit: 128m
