apiVersion: v1
kind: Pod
metadata:
  name: server-web-pod
  labels:
    env: dev
    app: frontend
spec:
  containers:
    - name: web
      image: nginx:alpine
    - name: devops
      image: sonarqube:alpine
