FROM node:20-alpine AS building

ARG DIR

WORKDIR /build

COPY ${DIR}/package*.json .

RUN npm install

COPY ${DIR}/ .

RUN npm run build

FROM nginx:alpine AS final

#WORKDIR /app

COPY --from=building /build/dist/app-simple/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]