apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: backend1
  template:
    metadata:
      labels:
        env: dev
        app: backend1
    spec:
      containers:
        - name: backend1
          image: localhost:5000/backend1
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          env:
            - name: PORT
              value: "3010"
            - name: BACKEND2
              value: http://backend2-svc/api/product
