services:
  server-web:
    image: nginx:stable-alpine
    container_name: server-web
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php-fpm:
    image: php:8.2.13-fpm-alpine3.18
    container_name: php-fpm
    ports:
      - "9050:9000"
    volumes:
      - ./src:/var/www/html
