apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: backend1
  template:
    metadata:
      labels:
        env: dev
        app: backend1
    spec:
      containers:
        - name: backend1
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/backend1
          imagePullPolicy: Always
          ports:
            - containerPort: 3010
          env:
            - name: PORT
              value: "3010"
            - name: BACKEND2
              value: http://backend2-svc/api/product
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3010
            initialDelaySeconds: 3
            periodSeconds: 3
