services:
  server-web:
    container_name: server-web
    image: nginx:stable-alpine
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    cpus: 0.5
    mem_limit: 128m

  php:
    container_name: php
    image: php:8.2.13-fpm-alpine3.18
    volumes:
      - ./src:/var/www/html
    cpus: 0.5
    mem_limit: 128m
